version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1337:1337"
    env_file:
      - .env
    networks:
      - backend
    environment:
      - HOST=0.0.0.0

networks:
  backend:
    external: true